"""gimbal.capture.cli — start / list / show / archive 4 子命令的实现。

注册位置: `gimbal/cli/capture.py` (typer app)。

v0.4 变更 (Capture Filter Strategy):
  - start 新增 4 个 typer 参数: --filter-file / --filter-profile / --filter-mode / --strict-files-only
  - 父进程先 build_matcher 一次, 提前发现 YAML 错 / 正则错 / 循环 include
  - addon 脚本注入 build_matcher, mitmdump 子进程独立构造 CompiledMatcher
  - 旧 `--filter CSV` 行为完全保留 (走 CSV 路径或 sentinel 兜底)
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

import typer

from .archive import archive_session, list_active
from .bus import FileBus, SessionLockedError
from .loader import FilterConfigError, build_matcher
from .strategy import FilterMode


def resolve_home(home: Optional[Path]) -> Path:
    """解析 $GIMBAL_HOME: 优先参数,其次环境变量,最后 ~/.gimbal。"""
    if home is not None:
        return home.expanduser()
    import os
    env = os.environ.get("GIMBAL_HOME")
    if env:
        return Path(env).expanduser()
    return Path("~/.gimbal").expanduser()


# ─── start ──────────────────────────────────────────────────────────────────


def _render_addon_script(
    home: Path,
    session: str,
    *,
    filter_file: Optional[Path],
    filter_profile: Optional[str],
    cli_csv: str,
    cli_mode: str,
) -> str:
    """渲染 mitmdump -s 加载的临时 addon 脚本。

    脚本在 mitmdump 子进程里执行, 通过 home/session/filter 创建 FileBus 与 matcher。
    v0.4 走 build_matcher 端到端入口。
    """
    home_s = str(home).replace("\\", "\\\\")
    filter_csv_s = cli_csv.replace("\\", "\\\\").replace('"', '\\"')
    if filter_file is not None:
        file_repr = f'r"{str(filter_file).replace(chr(92), chr(92) * 2)}"'
    else:
        file_repr = "None"
    profile_repr = f'"{filter_profile}"' if filter_profile else "None"

    return f'''# Auto-generated by gimbal capture; do not edit.
import sys
from pathlib import Path

# 把 gimbal 包根加进 sys.path (mitmdump 子进程的 CWD 可能不是项目根)
sys.path.insert(0, r"{Path(__file__).resolve().parent.parent.parent.parent}")

from gimbal.capture.bus import FileBus
from gimbal.capture.loader import build_matcher
from gimbal.capture.proxy import CaptureAddon
from gimbal.capture.strategy import FilterMode

home = Path(r"{home_s}")
session = "{session}"
cli_csv = "{filter_csv_s}"
cli_mode = "{cli_mode}"

bus = FileBus(home, session)
matcher = build_matcher(
    filter_file={file_repr},
    profile={profile_repr},
    cli_csv=cli_csv,
    cli_mode=FilterMode(cli_mode),
)

addons = [CaptureAddon(bus, matcher)]
'''


def start_cmd(
    session: str = typer.Option(..., "--session", "-s", help="会话 ID"),
    port: int = typer.Option(8080, "--port", "-p"),
    filter: str = typer.Option("/api/", "--filter", "-f"),
    home: Optional[Path] = typer.Option(None, "--home"),
    mitmdump: str = typer.Option("mitmdump", help="mitmdump 可执行文件"),
    # ── v0.4 新增 ─────────────────────────────────────────────────────────
    filter_file: Optional[Path] = typer.Option(
        None,
        "--filter-file",
        help="YAML 筛选配置文件; 未传则按 .gimbal/filters.yaml 等自动查找",
    ),
    filter_profile: Optional[str] = typer.Option(
        None,
        "--filter-profile",
        help="要使用的 profile 名; 多 profile 时必填",
    ),
    filter_mode: FilterMode = typer.Option(
        FilterMode.INCLUDE,
        "--filter-mode",
        help="CLI --filter 追加规则的默认 mode (include / exclude)",
    ),
    strict_files_only: bool = typer.Option(
        False,
        "--strict-files-only",
        help="关闭自动文件查找, 只用 --filter-file",
    ),
) -> None:
    """启动 mitmproxy 抓包, Ctrl+C 停止并自动归档。

    v0.5.2.1 修复: 父进程**不创建** FileBus (避免与 addon 子进程抢 lock).
    父进程用 probe_bus 即建即关, addon 进程才是 FileBus 的唯一持有者.
    """
    home = resolve_home(home)
    home.mkdir(parents=True, exist_ok=True)

    # 父进程提前校验: 立刻发现 YAML 错 / 正则错 / 循环 include
    try:
        matcher = build_matcher(
            filter_file=filter_file,
            profile=filter_profile,
            cli_csv=filter,
            cli_mode=filter_mode,
            strict_files_only=strict_files_only,
        )
    except FilterConfigError as e:
        typer.secho(
            f"[capture] 筛选配置错误: {e}",
            fg=typer.colors.RED, err=True,
        )
        raise typer.Exit(5)
    typer.echo(f"[capture] filter rules: {len(matcher.rules)} (mode={filter_mode.value})")

    # 残留检测: 文件已存在则试探 dev-{sid} 的 lock (即建即关)
    active_path = home / "captures" / "active" / f"{session}.ndjson"
    if active_path.exists():
        try:
            # 抢 dev-{sid}.lock (O_CREAT|O_EXCL), 立即关
            probe = FileBus(home, session)
            probe.close()
            # 探测成功 → 真的没人写
            if not typer.confirm(
                f"session '{session}' 已有残留数据 {active_path.stat().st_size} bytes,如何处理?",
                default=False,
            ):
                raise typer.Exit(1)
            active_path.write_text("", encoding="utf-8")
        except SessionLockedError:
            typer.secho(
                f"[capture] session '{session}' 已被另一个进程占用",
                fg=typer.colors.RED, err=True,
            )
            raise typer.Exit(4)

    # 渲染临时 addon 脚本 (addon 进程会自己创建 FileBus, 抢 lock)
    addon_script = _render_addon_script(
        home, session,
        filter_file=filter_file,
        filter_profile=filter_profile,
        cli_csv=filter,
        cli_mode=filter_mode.value,
    )
    tmp_script = home / ".tmp_capture_addon.py"
    tmp_script.write_text(addon_script, encoding="utf-8")

    cmd = [
        mitmdump,
        "-s", str(tmp_script),
        "-p", str(port),
        "-q",
        "--set", f"capture_home={home}",
        "--set", f"capture_session={session}",
        "--set", f"capture_filter={filter}",
    ]
    typer.echo(
        f"[capture] session={session}  port={port}  filter-file={filter_file}  profile={filter_profile}"
    )
    typer.echo(f"[capture] out={active_path}")
    typer.echo("[capture] 浏览器代理指向 127.0.0.1:8080, 信任 mitmproxy CA (http://mitm.it)")

    try:
        proc = subprocess.Popen(cmd)
        proc.wait()
    except KeyboardInterrupt:
        typer.echo("\n[capture] stopping...")
    finally:
        # 父进程无 FileBus, 不需要 close. addon 进程已自己 close (mitmdump 退出时)
        archive_session(home, session)
        tmp_script.unlink(missing_ok=True)
        typer.echo(f"[capture] archived → {home}/captures/archive/")


# ─── list ───────────────────────────────────────────────────────────────────


def list_sessions_cmd(home: Optional[Path] = typer.Option(None, "--home")) -> None:
    """列出 active 下所有 session。"""
    home = resolve_home(home)
    active = list_active(home)
    if not active:
        typer.echo("(无 active session)")
        return
    for p in active:
        size = p.stat().st_size
        mtime = datetime.fromtimestamp(p.stat().st_mtime)
        typer.echo(f"{p.stem:<30} {size:>10} bytes  {mtime:%Y-%m-%d %H:%M:%S}")


# ─── show ───────────────────────────────────────────────────────────────────


def show_session_cmd(
    session: str = typer.Argument(..., help="会话 ID"),
    home: Optional[Path] = typer.Option(None, "--home"),
    limit: int = typer.Option(50, "--limit", "-n"),
) -> None:
    """查看某 session 的事件(默认最近 50 条)。"""
    home = resolve_home(home)
    path = home / "captures" / "active" / f"{session}.ndjson"
    if not path.exists():
        typer.secho(f"session 不存在: {session}", fg=typer.colors.RED, err=True)
        raise typer.Exit(1)
    with path.open("r", encoding="utf-8") as f:
        lines = f.readlines()
    for line in lines[-limit:]:
        ev = json.loads(line)
        typer.echo(
            f"{ev['method']:<6} {ev['host']}{ev['path']:<40} {ev['response']['status']}"
        )


# ─── archive ────────────────────────────────────────────────────────────────


def archive_cmd(
    session: str = typer.Argument(..., help="会话 ID"),
    home: Optional[Path] = typer.Option(None, "--home"),
) -> None:
    """手动归档一个 session(从 active 移到 archive)。"""
    home = resolve_home(home)
    dst = archive_session(home, session)
    if dst:
        typer.echo(f"已归档 → {dst}")
    else:
        typer.secho(f"session 不存在: {session}", fg=typer.colors.RED, err=True)
        raise typer.Exit(1)
